[package]
name = "webrtc-unreliable"
version = "0.4.0-alpha.0"
authors = ["kyren <kerriganw@gmail.com>"]
edition = "2018"
description = "UDP-like (unreliable, unordered) communication between Javascript/WebAssembly and native Rust via WebRTC"
repository = "https://github.com/kyren/webrtc-unreliable"
documentation = "https://docs.rs/webrtc-unreliable"
readme = "README.md"
keywords = ["wasm", "webrtc"]
license = "MIT"

[dependencies]
byteorder = "1.3"
crc32c = "0.4"
crc32fast = "1.2"
crossbeam = "0.7"
futures-channel = { package = "futures-channel-preview", version = "0.3.0-alpha.19", features = ["sink"] }
futures-core = { package = "futures-core-preview", version = "0.3.0-alpha.19" }
futures-sink = { package = "futures-sink-preview", version = "0.3.0-alpha.19" }
futures-util = { package = "futures-util-preview", version = "0.3.0-alpha.19", features = ["sink", "select-macro"] }
http = "0.1.17"
log = "0.4"
openssl = "0.10"
rand = "0.7"
tokio-net = { version = "0.2.0-alpha.6", features = ["udp"] }
tokio-timer = { version = "0.3.0-alpha.6", features = ["async-traits"] }

[dev-dependencies]
clap = "2.32"
env_logger = "0.6"
hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
futures = { package = "futures-preview", version = "0.3.0-alpha.19" }
tokio = "0.2.0-alpha.6"
