[package]
name = "rtcdata"
version = "0.1.0"
authors = ["kyren <kerriganw@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
clap = "2.32"
crc32c = "0.4"
crc32fast = "1.2"
crossbeam = "0.7"
futures = "0.1"
hyper = "0.12"
log = "0.4"
openssl = "0.10"
rand = "0.6"
tokio = "0.1"

hexdump = "*"

[dev-dependencies]
env_logger = "0.6"