version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    environment:
      RUST_TOOLCHAIN: nightly
    steps:
      - checkout
      - run:
          name: rustup installation
          command: |
            rustup toolchain install nightly
            rustup component add rustfmt-preview
      - run:
          name: Version information
          command: |
            rustc --version
            cargo --version
            rustfmt --version
            rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt --all -- --check --color=auto
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
